### ISSUE TITLE
漏网之鱼

### ISSUE THREAD

**Issue by Pandaver** [Hazx/ikuai_ban_overseas#1]
![截图_20241030201221](https://github.com/user-attachments/assets/8660ab56-7e2d-4d98-a781-ab6eac9be114)
一直打我烦死了

**Comment by Hazx** [comment]
我用的那个ip库不是很全，会有一些漏网之鱼，需要手工再创建和维护一个黑名单IP表，把漏掉的并且发现正在攻击的IP加进去.. 针对你这个情况，在【IP分组】中新建一项“黑名单”IP组，把185.147.124.0/24添进去；然后在【ACL规则】中编辑已经添进去的屏蔽境外IP那条规则，把这个新加的IP分组加进去。以后再有新的IP需要屏蔽，只需要在那个新IP分组里添加就行了。
